apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-springboot-3
  namespace: sandbox-test-springboot-3
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/tags: sandbox=test-springboot-3,tenant=mastercard,CostCenter=MC-1234
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-springboot-3
                port:
                  number: 80
